//
// Color.kt
//
// SPDX-FileCopyrightText: 2022 Istituto Nazionale Previdenza Sociale
//
// SPDX-License-Identifier: BSD-3-Clause
//

package it.inps.sirio.theme

import androidx.annotation.Keep
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Stable
import androidx.compose.ui.graphics.Color
import it.inps.sirio.ui.accordion.SirioAccordionColors
import it.inps.sirio.ui.button.SirioButtonColors
import it.inps.sirio.ui.pagination.SirioPaginationColors
import it.inps.sirio.styleDictionary.StyleDictionaryColor
import it.inps.sirio.ui.dialog.SirioDialogColors
import it.inps.sirio.ui.searchbar.SirioSearchBarColors
import it.inps.sirio.ui.tabs.SirioTabsColors
import it.inps.sirio.ui.textfield.SirioTextFieldColors

internal val LightColorPalette = SirioColors(
    brand = StyleDictionaryColor.colorGlobalPrimary100,
    fabDefaultBackground = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
    fabHoverBackground = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
    fabFocusBackground = StyleDictionaryColor.colorAliasInteractivePrimaryFocus,
    fabBorderFocus = StyleDictionaryColor.colorAliasInteractiveBorderFocus,
    fabPressedBackground = StyleDictionaryColor.colorAliasInteractivePrimaryPressed,
    fabContent = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
    appNavigationBackground = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
    appNavigationIcon = StyleDictionaryColor.colorAliasAppInteractiveSecondaryDefault,
    appNavigationIconPressed = StyleDictionaryColor.colorAliasOverlay15Secondary100,
    appNavigationText = StyleDictionaryColor.colorAliasTextColorPrimaryDark110,
    appNavigationUsernameBackground = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight50,
    appNavigationUsernameText = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
    appNavigationSearchBackground1 = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
    appNavigationSearchBackground2 = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight40,
    appNavigationSearchText = StyleDictionaryColor.colorAliasAppInteractiveSecondaryDefault,
    appNavigationSearchIcon = StyleDictionaryColor.colorAliasAppInteractiveSecondaryDefault,
    tabBarBackground = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
    tabBarContent = StyleDictionaryColor.colorAliasAppInteractiveSecondaryDefault,
    tabBarActive = StyleDictionaryColor.colorAliasAppInteractivePrimaryActive,
    tagGrayBackground = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
    tagBlueBackground = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
    tagRedBackground = StyleDictionaryColor.colorAliasInteractiveRedDefault,
    tagOrangeBackground = StyleDictionaryColor.colorGlobalSemanticWarning100,
    tagGreenBackground = StyleDictionaryColor.colorGlobalSemanticSuccesso100,
    tagWhiteBackground = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
    tagGrayText = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
    tagBlueText = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
    tagRedText = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
    tagOrangeText = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
    tagGreenText = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
    tagWhiteText = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
    accordion = SirioAccordionColors(
        activedBackground = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight40,
        activedBorder = Color.Transparent,
        contentBackground = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
        contentBorder = StyleDictionaryColor.colorGlobalLightPrimary50,
        background = SirioColorState(
            default = StyleDictionaryColor.colorGlobalPrimary000,
            disabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
            focused = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight40,
            hovered = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight40,
            pressed = StyleDictionaryColor.colorGlobalPrimary000,
        ),
        content = SirioColorState.all(
            color = StyleDictionaryColor.colorAliasTextColorPrimaryDark110,
            disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
        ),
        border = SirioColorState(
            default = StyleDictionaryColor.colorGlobalLightPrimary50,
            disabled = Color.Transparent,
            focused = StyleDictionaryColor.colorAliasInteractiveBorderFocus,
            hovered = StyleDictionaryColor.colorGlobalLightPrimary50,
            pressed = Color.Transparent,
        ),
    ),
    chipDefaultBackground = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
    chipHoverBackground = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
    chipFocusBackground = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
    chipPressedBackground = StyleDictionaryColor.colorAliasInteractivePrimaryPressed,
    chipDisabledBackground = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
    chipWithCloseDefaultBackground = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
    chipWithCloseHoverBackground = StyleDictionaryColor.colorAliasInteractiveSecondaryHover,
    chipWithCloseFocusBackground = StyleDictionaryColor.colorAliasInteractiveSecondaryHover,
    chipWithClosePressedBackground = StyleDictionaryColor.colorAliasInteractiveSecondaryPressed,
    chipWithCloseDisabledBackground = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
    chipDefaultButtonBackground = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
    chipHoverButtonBackground = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
    chipFocusButtonBackground = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
    chipPressedButtonBackground = StyleDictionaryColor.colorAliasInteractivePrimaryPressed,
    chipDisabledButtonBackground = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
    chipButtonBorder = StyleDictionaryColor.colorGlobalMidPrimary70,
    chipFocusBorder = StyleDictionaryColor.colorAliasInteractiveBorderFocus,
    chipContent = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
    chipDisabledContent = StyleDictionaryColor.colorAliasTextColorDisabled,
    chipDisactiveBackground = Color.Transparent,
    checkboxBackground = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
    checkboxDefaultContent = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
    checkboxHoverContent = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
    checkboxFocusContent = StyleDictionaryColor.colorSpecificDataEntryBorderColorFocus,
    checkboxFocusBorder = StyleDictionaryColor.colorAliasInteractiveBorderFocus,
    checkboxPressed = StyleDictionaryColor.colorAliasInteractivePrimaryPressed,
    checkboxPressedText = StyleDictionaryColor.colorSpecificDataEntryLabelColorValued,
    checkboxDisabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
    checkboxDisabledContent = StyleDictionaryColor.colorAliasTextColorDisabled,
    radioBackground = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
    radioDefault = StyleDictionaryColor.colorSpecificDataEntryLabelColorDefault,
    radioHover = StyleDictionaryColor.colorSpecificDataEntryLabelColorHover,
    radioFocus = StyleDictionaryColor.colorSpecificDataEntryLabelColorFocus,
    radioFocusBorder = StyleDictionaryColor.colorAliasInteractiveBorderFocus,
    radioPressed = StyleDictionaryColor.colorSpecificDataEntryLabelColorValued,
    radioDisabled = StyleDictionaryColor.colorAliasTextColorDisabled,
    radioDisabledBorder = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
    toggleBackground = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
    toggleDefaultOff = StyleDictionaryColor.colorSpecificDataEntryBorderColorDefault,
    toggleDefaultOn = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
    toggleHoverOff = StyleDictionaryColor.colorAliasInteractiveSecondaryHover,
    toggleHoverOn = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
    toggleFocusOff = StyleDictionaryColor.colorAliasInteractiveSecondaryFocus,
    toggleFocusOn = StyleDictionaryColor.colorAliasInteractivePrimaryFocus,
    toggleFocusExtraBorder = StyleDictionaryColor.colorAliasInteractiveBorderFocus,
    toggleDisabled = StyleDictionaryColor.colorAliasTextColorDisabled,
    toggleDisabledBorder = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
    sliderThumb = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
    sliderPressedThumb = StyleDictionaryColor.colorSpecificOptionBackgroundColorPressed,
    sliderDisabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
    sliderInactive = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
    sliderActive = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
    sliderFocusActive = StyleDictionaryColor.colorAliasInteractiveBorderFocus,
    sliderPressedActive = StyleDictionaryColor.colorSpecificOptionBackgroundColorPressed,
    sliderTitle = StyleDictionaryColor.colorSpecificDataEntryLabelColorDefault,
    sliderText = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
    sliderNumbers = StyleDictionaryColor.colorAliasTextColorSecondaryDark100,
    sliderDefaultTextFieldBackground = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
    sliderDisabledTextFieldBackground = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
    sliderDefaultTextFieldBorder = StyleDictionaryColor.colorSpecificDataEntryBorderColorDefault,
    sliderDefaultTextFieldText = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorDefault,
    sliderHoverTextFieldBorder = StyleDictionaryColor.colorSpecificDataEntryBorderColorHover,
    sliderHoverTextFieldText = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorHover,
    sliderFocusTextFieldExtraBorder = StyleDictionaryColor.colorAliasInteractiveBorderFocus,
    sliderFocusTextFieldBorder = StyleDictionaryColor.colorAliasInteractivePrimaryFocus,
    sliderFocusTextFieldText = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorFocus,
    sliderPressedTextFieldBorder = StyleDictionaryColor.colorSpecificDataEntryBorderColorValued,
    sliderPressedTextFieldText = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorValued,
    sliderDisabledTextFieldBorder = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
    sliderDisabledTextFieldText = StyleDictionaryColor.colorAliasTextColorDisabled,
    progressBarLabel = StyleDictionaryColor.colorSpecificDataEntryLabelColorDefault,
    progressBarNumber = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
    progressBarBackground = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight40,
    progressBarGradient = StyleDictionaryColor.colorSpecificProgressbarBackgroundColor,
    buttons = ButtonColors(
        buttonFocusExtraBorder = StyleDictionaryColor.colorAliasInteractiveBorderFocus,
        buttonPrimary = SirioButtonColors(
            background = SirioColorState(
                default = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
                hovered = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
                focused = StyleDictionaryColor.colorAliasInteractivePrimaryFocus,
                pressed = StyleDictionaryColor.colorAliasInteractivePrimaryPressed,
                disabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
            ),
            border = null,
            content = SirioColorState.all(
                color = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
                disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            ),
        ),
        buttonDanger = SirioButtonColors(
            background = SirioColorState(
                default = StyleDictionaryColor.colorAliasInteractiveRedDefault,
                hovered = StyleDictionaryColor.colorAliasInteractiveRedHover,
                focused = StyleDictionaryColor.colorAliasInteractiveRedFocus,
                pressed = StyleDictionaryColor.colorAliasInteractiveRedPressed,
                disabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
            ),
            border = null,
            content = SirioColorState.all(
                color = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
                disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            ),
        ),
        buttonSecondary = SirioButtonColors(
            background = SirioColorState(
                default = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
                hovered = StyleDictionaryColor.colorAliasInteractiveSecondaryHover,
                focused = StyleDictionaryColor.colorAliasInteractiveSecondaryFocus,
                pressed = StyleDictionaryColor.colorAliasInteractiveSecondaryPressed,
                disabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
            ),
            border = null,
            content = SirioColorState.all(
                color = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
                disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            ),
        ),
        buttonTertiary = SirioButtonColors(
            background = SirioColorState.all(Color.Transparent),
            border = SirioColorState(
                default = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
                hovered = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
                focused = StyleDictionaryColor.colorAliasInteractivePrimaryFocus,
                pressed = StyleDictionaryColor.colorAliasInteractivePrimaryPressed,
                disabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
            ),
            content = SirioColorState(
                default = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
                hovered = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
                focused = StyleDictionaryColor.colorAliasInteractivePrimaryFocus,
                pressed = StyleDictionaryColor.colorAliasInteractivePrimaryPressed,
                disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            ),
        ),
        buttonGhost = SirioButtonColors(
            background = SirioColorState(
                default = Color.Transparent,
                focused = Color.Transparent,
                hovered = Color.Transparent,
                pressed = StyleDictionaryColor.colorAliasInteractivePrimaryPressed,
                disabled = Color.Transparent,
            ),
            border = SirioColorState.all(Color.Transparent),
            content = SirioColorState(
                default = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
                hovered = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
                focused = StyleDictionaryColor.colorAliasInteractivePrimaryFocus,
                pressed = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
                disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            ),
        ),
    ),
    fileUploadTitle = StyleDictionaryColor.colorSpecificDataEntryLabelColorDefault,
    fileUploadText = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
    notificationColors = NotificationColors(
        background = StyleDictionaryColor.colorAliasBackgroundColorPrimaryDark120,
        title = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
        text = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
        icon = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
        close = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
        alert = StyleDictionaryColor.colorGlobalSemanticAlert100,
        info = StyleDictionaryColor.colorGlobalSemanticInfo100,
        warning = StyleDictionaryColor.colorGlobalSemanticWarning100,
        success = StyleDictionaryColor.colorGlobalSemanticSuccesso100,
    ),
    textField = SirioTextFieldColors(
        background = SirioColorState.all(Color.Transparent),
        extraBorder = StyleDictionaryColor.colorAliasInteractiveBorderFocus,
        border = SirioColorState(
            default = StyleDictionaryColor.colorSpecificDataEntryBorderColorDefault,
            disabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
            focused = StyleDictionaryColor.colorSpecificDataEntryBorderColorFocus,
            hovered = StyleDictionaryColor.colorSpecificDataEntryBorderColorHover,
            pressed = StyleDictionaryColor.colorSpecificDataEntryBorderColorValued,
            alert = StyleDictionaryColor.colorSpecificDataEntryBorderColorError,
            warning = StyleDictionaryColor.colorSpecificDataEntryBorderColorWarning,
            success = StyleDictionaryColor.colorSpecificDataEntryBorderColorSuccess,
            info = StyleDictionaryColor.colorSpecificDataEntryBorderColorDefault,
        ),
        dropdown = SirioColorState.all(StyleDictionaryColor.colorAliasInteractiveSecondaryDefault),
        optionBackground = SirioColorState(
            default = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
            disabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
            focused = StyleDictionaryColor.colorSpecificOptionBackgroundColorFocus,
            hovered = StyleDictionaryColor.colorSpecificOptionBackgroundColorHover,
            pressed = StyleDictionaryColor.colorSpecificOptionBackgroundColorPressed,
        ),
        optionText = SirioColorState(
            default = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorDefault,
            disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            focused = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
            hovered = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
            pressed = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
        ),
        label = SirioColorState(
            default = StyleDictionaryColor.colorSpecificDataEntryLabelColorDefault,
            disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            focused = StyleDictionaryColor.colorSpecificDataEntryLabelColorFocus,
            hovered = StyleDictionaryColor.colorSpecificDataEntryLabelColorHover,
            pressed = StyleDictionaryColor.colorSpecificDataEntryLabelColorValued,
            alert = StyleDictionaryColor.colorSpecificDataEntryBorderColorError,
            warning = StyleDictionaryColor.colorSpecificDataEntryBorderColorWarning,
            success = StyleDictionaryColor.colorSpecificDataEntryBorderColorSuccess,
            info = StyleDictionaryColor.colorSpecificDataEntryLabelColorDefault,
        ),
        icon = SirioColorState(
            default = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
            disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            focused = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
            hovered = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
            pressed = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
            alert = StyleDictionaryColor.colorSpecificDataEntryBorderColorError,
            warning = StyleDictionaryColor.colorSpecificDataEntryBorderColorWarning,
            success = StyleDictionaryColor.colorSpecificDataEntryBorderColorSuccess,
            info = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
        ),
        helperText = SirioColorState(
            default = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
            disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            focused = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
            hovered = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
            pressed = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
            alert = StyleDictionaryColor.colorGlobalSemanticAlert100,
            warning = StyleDictionaryColor.colorGlobalSemanticWarning100,
            success = StyleDictionaryColor.colorGlobalSemanticSuccesso100,
            info = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
        ),
        placeholder = SirioColorState(
            default = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorDefault,
            disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            focused = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorFocus,
            hovered = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorHover,
            pressed = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorValued,
            alert = StyleDictionaryColor.colorSpecificDataEntryBorderColorError,
            warning = StyleDictionaryColor.colorSpecificDataEntryBorderColorWarning,
            success = StyleDictionaryColor.colorSpecificDataEntryBorderColorSuccess,
            info = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorDefault,
        ),
        text = SirioColorState(
            default = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorDefault,
            disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            focused = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorFocus,
            hovered = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorHover,
            pressed = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorValued,
            alert = StyleDictionaryColor.colorSpecificDataEntryBorderColorError,
            warning = StyleDictionaryColor.colorSpecificDataEntryBorderColorWarning,
            success = StyleDictionaryColor.colorSpecificDataEntryBorderColorSuccess,
            info = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorDefault,
        ),
    ),
    pagination = SirioPaginationColors(
        background = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
        tile = SirioColorState(
            default = Color.Transparent,
            disabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
            focused = Color.Transparent,
            hovered = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
            pressed = StyleDictionaryColor.colorAliasInteractivePrimaryPressed,
        ),
        tileBorder = SirioColorState(
            default = Color.Transparent,
            disabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
            focused = StyleDictionaryColor.colorAliasInteractiveBorderFocus,
            hovered = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
            pressed = StyleDictionaryColor.colorAliasInteractivePrimaryPressed,
        ),
        number = SirioColorState(
            default = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
            disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            focused = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
            hovered = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
            pressed = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
        )
    ),
    tabs = SirioTabsColors(
        backgroundBottomSelection = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
        backgroundTopSelection = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight40,
        backgroundSelected = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
        backgroundBottomSelectionDisabled = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
        backgroundTopSelectionDisabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
        text = SirioColorState(
            default = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
            hovered = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
            focused = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
            pressed = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
            disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
        ),
        icon = SirioColorState(
            default = StyleDictionaryColor.colorAliasTextColorPrimaryLight50,
            hovered = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
            focused = StyleDictionaryColor.colorAliasInteractivePrimaryFocus,
            pressed = StyleDictionaryColor.colorAliasAppInteractivePrimaryActive,
            disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
        ),
        selection = SirioColorState(
            default = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight40,
            hovered = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
            focused = StyleDictionaryColor.colorAliasInteractivePrimaryFocus,
            pressed = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
            disabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
        ),
    ),
    searchBar = SirioSearchBarColors(
        background = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
    ),
    dialog = SirioDialogColors(
        background = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
        semanticDefault = StyleDictionaryColor.colorGlobalSemanticInfo100,
        semanticAlert = StyleDictionaryColor.colorGlobalSemanticAlert100,
        semanticWarning = StyleDictionaryColor.colorGlobalSemanticWarning100,
        title = StyleDictionaryColor.colorAliasTextColorSecondaryDark100,
        text = StyleDictionaryColor.colorAliasTextColorSecondaryDark100,
    ),
    isDark = false,
)

internal val DarkColorPalette = SirioColors(
    brand = StyleDictionaryColor.colorGlobalPrimary000,
    fabDefaultBackground = StyleDictionaryColor.colorAliasAppInteractivePrimary000Default,
    fabHoverBackground = StyleDictionaryColor.colorAliasInteractiveAccentHover,
    fabFocusBackground = StyleDictionaryColor.colorAliasAppInteractivePrimary000Default,
    fabBorderFocus = StyleDictionaryColor.colorAliasInteractiveBorderFocus,
    fabPressedBackground = StyleDictionaryColor.colorAliasInteractiveAccentDefault,
    fabContent = StyleDictionaryColor.colorAliasTextColorPrimaryDark110,
    appNavigationBackground = StyleDictionaryColor.colorAliasBackgroundColorPrimaryDark120,
    appNavigationIcon = StyleDictionaryColor.colorAliasAppInteractivePrimary000Default,
    appNavigationIconPressed = StyleDictionaryColor.colorAliasOverlay25Primary000,
    appNavigationText = StyleDictionaryColor.colorAliasTextColorPrimaryLight50,
    appNavigationUsernameBackground = StyleDictionaryColor.colorAliasBackgroundColorPrimaryDark115,
    appNavigationUsernameText = StyleDictionaryColor.colorAliasInteractivePrimary000Default,
    appNavigationSearchBackground1 = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
    appNavigationSearchBackground2 = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight40,
    appNavigationSearchText = StyleDictionaryColor.colorAliasAppInteractiveSecondaryDefault,
    appNavigationSearchIcon = StyleDictionaryColor.colorAliasAppInteractiveSecondaryDefault,
    tabBarBackground = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
    tabBarContent = StyleDictionaryColor.colorAliasAppInteractiveSecondaryDefault,
    tabBarActive = StyleDictionaryColor.colorAliasAppInteractivePrimaryActive,
    tagGrayBackground = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
    tagBlueBackground = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
    tagRedBackground = StyleDictionaryColor.colorAliasInteractiveRedDefault,
    tagOrangeBackground = StyleDictionaryColor.colorGlobalSemanticWarning100,
    tagGreenBackground = StyleDictionaryColor.colorGlobalSemanticSuccesso100,
    tagWhiteBackground = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
    tagGrayText = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
    tagBlueText = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
    tagRedText = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
    tagOrangeText = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
    tagGreenText = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
    tagWhiteText = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
    accordion = SirioAccordionColors(
        activedBackground = StyleDictionaryColor.colorAliasInteractivePrimaryPressed,
        activedBorder = Color.Transparent,
        contentBackground = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
        contentBorder = StyleDictionaryColor.colorGlobalLightPrimary50,
        background = SirioColorState(
            default = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
            disabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
            focused = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
            hovered = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
            pressed = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
        ),
        content = SirioColorState.all(
            color = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
            disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
        ),
        border = SirioColorState(
            default = StyleDictionaryColor.colorGlobalLightPrimary50,
            disabled = Color.Transparent,
            focused = StyleDictionaryColor.colorAliasInteractiveBorderFocus,
            hovered = Color.Transparent,
            pressed = Color.Transparent,
        ),
    ),
    chipDefaultBackground = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
    chipHoverBackground = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
    chipFocusBackground = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
    chipPressedBackground = StyleDictionaryColor.colorAliasInteractivePrimaryPressed,
    chipDisabledBackground = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
    chipWithCloseDefaultBackground = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
    chipWithCloseHoverBackground = StyleDictionaryColor.colorAliasInteractiveSecondaryHover,
    chipWithCloseFocusBackground = StyleDictionaryColor.colorAliasInteractiveSecondaryHover,
    chipWithClosePressedBackground = StyleDictionaryColor.colorAliasInteractiveSecondaryPressed,
    chipWithCloseDisabledBackground = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
    chipDefaultButtonBackground = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
    chipHoverButtonBackground = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
    chipFocusButtonBackground = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
    chipPressedButtonBackground = StyleDictionaryColor.colorAliasInteractivePrimaryPressed,
    chipDisabledButtonBackground = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
    chipButtonBorder = StyleDictionaryColor.colorGlobalMidPrimary70,
    chipFocusBorder = StyleDictionaryColor.colorAliasInteractiveBorderFocus,
    chipContent = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
    chipDisabledContent = StyleDictionaryColor.colorAliasTextColorDisabled,
    chipDisactiveBackground = Color.Transparent,
    checkboxBackground = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
    checkboxDefaultContent = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
    checkboxHoverContent = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
    checkboxFocusContent = StyleDictionaryColor.colorSpecificDataEntryBorderColorFocus,
    checkboxFocusBorder = StyleDictionaryColor.colorAliasInteractiveBorderFocus,
    checkboxPressed = StyleDictionaryColor.colorAliasInteractivePrimaryPressed,
    checkboxPressedText = StyleDictionaryColor.colorSpecificDataEntryLabelColorValued,
    checkboxDisabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
    checkboxDisabledContent = StyleDictionaryColor.colorAliasTextColorDisabled,
    radioBackground = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
    radioDefault = StyleDictionaryColor.colorSpecificDataEntryLabelColorDefault,
    radioHover = StyleDictionaryColor.colorSpecificDataEntryLabelColorHover,
    radioFocus = StyleDictionaryColor.colorSpecificDataEntryLabelColorFocus,
    radioFocusBorder = StyleDictionaryColor.colorAliasInteractiveBorderFocus,
    radioPressed = StyleDictionaryColor.colorSpecificDataEntryLabelColorValued,
    radioDisabled = StyleDictionaryColor.colorAliasTextColorDisabled,
    radioDisabledBorder = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
    toggleBackground = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
    toggleDefaultOff = StyleDictionaryColor.colorSpecificDataEntryBorderColorDefault,
    toggleDefaultOn = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
    toggleHoverOff = StyleDictionaryColor.colorAliasInteractiveSecondaryHover,
    toggleHoverOn = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
    toggleFocusOff = StyleDictionaryColor.colorAliasInteractiveSecondaryFocus,
    toggleFocusOn = StyleDictionaryColor.colorAliasInteractivePrimaryFocus,
    toggleFocusExtraBorder = StyleDictionaryColor.colorAliasInteractiveBorderFocus,
    toggleDisabled = StyleDictionaryColor.colorAliasTextColorDisabled,
    toggleDisabledBorder = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
    sliderThumb = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
    sliderPressedThumb = StyleDictionaryColor.colorSpecificOptionBackgroundColorPressed,
    sliderDisabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
    sliderInactive = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
    sliderActive = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
    sliderFocusActive = StyleDictionaryColor.colorAliasInteractiveBorderFocus,
    sliderPressedActive = StyleDictionaryColor.colorSpecificOptionBackgroundColorPressed,
    sliderTitle = StyleDictionaryColor.colorSpecificDataEntryLabelColorDefault,
    sliderText = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
    sliderNumbers = StyleDictionaryColor.colorAliasTextColorSecondaryDark100,
    sliderDefaultTextFieldBackground = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
    sliderDisabledTextFieldBackground = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
    sliderDefaultTextFieldBorder = StyleDictionaryColor.colorSpecificDataEntryBorderColorDefault,
    sliderDefaultTextFieldText = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorDefault,
    sliderHoverTextFieldBorder = StyleDictionaryColor.colorSpecificDataEntryBorderColorHover,
    sliderHoverTextFieldText = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorHover,
    sliderFocusTextFieldExtraBorder = StyleDictionaryColor.colorAliasInteractiveBorderFocus,
    sliderFocusTextFieldBorder = StyleDictionaryColor.colorAliasInteractivePrimaryFocus,
    sliderFocusTextFieldText = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorFocus,
    sliderPressedTextFieldBorder = StyleDictionaryColor.colorSpecificDataEntryBorderColorValued,
    sliderPressedTextFieldText = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorValued,
    sliderDisabledTextFieldBorder = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
    sliderDisabledTextFieldText = StyleDictionaryColor.colorAliasTextColorDisabled,
    progressBarLabel = StyleDictionaryColor.colorSpecificDataEntryLabelColorDefault,
    progressBarNumber = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
    progressBarBackground = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight40,
    progressBarGradient = StyleDictionaryColor.colorSpecificProgressbarBackgroundColor,
    buttons = ButtonColors(
        buttonFocusExtraBorder = StyleDictionaryColor.colorAliasInteractiveBorderFocus,
        buttonPrimary = SirioButtonColors(
            background = SirioColorState(
                default = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
                hovered = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
                focused = StyleDictionaryColor.colorAliasInteractivePrimaryFocus,
                pressed = StyleDictionaryColor.colorAliasInteractivePrimaryPressed,
                disabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
            ),
            border = null,
            content = SirioColorState.all(
                color = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
                disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            ),
        ),
        buttonDanger = SirioButtonColors(
            background = SirioColorState(
                default = StyleDictionaryColor.colorAliasInteractiveRedDefault,
                hovered = StyleDictionaryColor.colorAliasInteractiveRedHover,
                focused = StyleDictionaryColor.colorAliasInteractiveRedFocus,
                pressed = StyleDictionaryColor.colorAliasInteractiveRedPressed,
                disabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
            ),
            border = null,
            content = SirioColorState.all(
                color = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
                disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            ),
        ),
        buttonSecondary = SirioButtonColors(
            background = SirioColorState(
                default = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
                hovered = StyleDictionaryColor.colorAliasInteractiveSecondaryHover,
                focused = StyleDictionaryColor.colorAliasInteractiveSecondaryFocus,
                pressed = StyleDictionaryColor.colorAliasInteractiveSecondaryPressed,
                disabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
            ),
            border = null,
            content = SirioColorState.all(
                color = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
                disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            ),
        ),
        buttonTertiary = SirioButtonColors(
            background = SirioColorState.all(Color.Transparent),
            border = SirioColorState(
                default = StyleDictionaryColor.colorAliasInteractiveAccentDefault,
                hovered = StyleDictionaryColor.colorAliasInteractiveAccentHover,
                focused = StyleDictionaryColor.colorAliasInteractiveAccentFocus,
                pressed = StyleDictionaryColor.colorAliasInteractiveAccentPressed,
                disabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
            ),
            content = SirioColorState(
                default = StyleDictionaryColor.colorAliasInteractiveAccentDefault,
                hovered = StyleDictionaryColor.colorAliasInteractiveAccentHover,
                focused = StyleDictionaryColor.colorAliasInteractiveAccentFocus,
                pressed = StyleDictionaryColor.colorAliasInteractiveAccentPressed,
                disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            ),
        ),
        buttonGhost = SirioButtonColors(
            background = SirioColorState(
                default = Color.Transparent,
                focused = Color.Transparent,
                hovered = Color.Transparent,
                pressed = StyleDictionaryColor.colorAliasInteractivePrimaryPressed,
                disabled = Color.Transparent,
            ),
            border = SirioColorState.all(Color.Transparent),
            content = SirioColorState(
                default = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
                hovered = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
                focused = StyleDictionaryColor.colorAliasInteractivePrimaryFocus,
                pressed = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
                disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            ),
        ),
    ),
    fileUploadTitle = StyleDictionaryColor.colorSpecificDataEntryLabelColorDefault,
    fileUploadText = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
    notificationColors = NotificationColors(
        background = StyleDictionaryColor.colorAliasBackgroundColorPrimaryDark120,
        title = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
        text = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
        icon = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
        close = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
        alert = StyleDictionaryColor.colorGlobalSemanticAlert100,
        info = StyleDictionaryColor.colorGlobalSemanticInfo100,
        warning = StyleDictionaryColor.colorGlobalSemanticWarning100,
        success = StyleDictionaryColor.colorGlobalSemanticSuccesso100,
    ),
    textField = SirioTextFieldColors(
        background = SirioColorState.all(Color.Transparent),
        extraBorder = StyleDictionaryColor.colorAliasInteractiveBorderFocus,
        border = SirioColorState(
            default = StyleDictionaryColor.colorSpecificDataEntryBorderColorDefault,
            disabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
            focused = StyleDictionaryColor.colorSpecificDataEntryLabelColorFocus,
            hovered = StyleDictionaryColor.colorSpecificDataEntryBorderColorHover,
            pressed = StyleDictionaryColor.colorSpecificDataEntryBorderColorValued,
            alert = StyleDictionaryColor.colorSpecificDataEntryBorderColorError,
            warning = StyleDictionaryColor.colorSpecificDataEntryBorderColorWarning,
            success = StyleDictionaryColor.colorSpecificDataEntryBorderColorSuccess,
            info = StyleDictionaryColor.colorSpecificDataEntryBorderColorDefault,
        ),
        dropdown = SirioColorState.all(StyleDictionaryColor.colorAliasInteractiveSecondaryDefault),
        optionBackground = SirioColorState(
            default = Color.Transparent,
            disabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
            focused = StyleDictionaryColor.colorSpecificOptionBackgroundColorFocus,
            hovered = StyleDictionaryColor.colorSpecificOptionBackgroundColorHover,
            pressed = StyleDictionaryColor.colorSpecificOptionBackgroundColorPressed,
        ),
        optionText = SirioColorState(
            default = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorDefault,
            disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            focused = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
            hovered = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
            pressed = StyleDictionaryColor.colorAliasTextColorPrimaryLight0,
        ),
        label = SirioColorState(
            default = StyleDictionaryColor.colorSpecificDataEntryLabelColorDefault,
            disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            focused = StyleDictionaryColor.colorSpecificDataEntryLabelColorFocus,
            hovered = StyleDictionaryColor.colorSpecificDataEntryLabelColorHover,
            pressed = StyleDictionaryColor.colorSpecificDataEntryLabelColorValued,
            alert = StyleDictionaryColor.colorSpecificDataEntryBorderColorError,
            warning = StyleDictionaryColor.colorSpecificDataEntryBorderColorWarning,
            success = StyleDictionaryColor.colorSpecificDataEntryBorderColorSuccess,
            info = StyleDictionaryColor.colorSpecificDataEntryLabelColorDefault,
        ),
        icon = SirioColorState(
            default = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
            disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            focused = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
            hovered = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
            pressed = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
            alert = StyleDictionaryColor.colorSpecificDataEntryBorderColorError,
            warning = StyleDictionaryColor.colorSpecificDataEntryBorderColorWarning,
            success = StyleDictionaryColor.colorSpecificDataEntryBorderColorSuccess,
            info = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
        ),
        helperText = SirioColorState(
            default = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
            disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            focused = StyleDictionaryColor.colorAliasInteractivePrimaryDefault,
            hovered = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
            pressed = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
            alert = StyleDictionaryColor.colorGlobalSemanticAlert100,
            warning = StyleDictionaryColor.colorGlobalSemanticWarning100,
            success = StyleDictionaryColor.colorGlobalSemanticSuccesso100,
            info = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
        ),
        placeholder = SirioColorState(
            default = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorDefault,
            disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            focused = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorFocus,
            hovered = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorHover,
            pressed = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorValued,
            alert = StyleDictionaryColor.colorSpecificDataEntryBorderColorError,
            warning = StyleDictionaryColor.colorSpecificDataEntryBorderColorWarning,
            success = StyleDictionaryColor.colorSpecificDataEntryBorderColorSuccess,
            info = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorDefault,
        ),
        text = SirioColorState(
            default = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorDefault,
            disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            focused = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorFocus,
            hovered = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorHover,
            pressed = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorValued,
            alert = StyleDictionaryColor.colorSpecificDataEntryBorderColorError,
            warning = StyleDictionaryColor.colorSpecificDataEntryBorderColorWarning,
            success = StyleDictionaryColor.colorSpecificDataEntryBorderColorSuccess,
            info = StyleDictionaryColor.colorSpecificDataEntryPlaceholderColorDefault,
        ),
    ),
    pagination = SirioPaginationColors(
        background = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
        tile = SirioColorState(
            default = Color.Transparent,
            disabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
            focused = Color.Transparent,
            hovered = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
            pressed = StyleDictionaryColor.colorAliasInteractivePrimaryPressed,
        ),
        tileBorder = SirioColorState(
            default = Color.Transparent,
            disabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
            focused = StyleDictionaryColor.colorAliasInteractiveBorderFocus,
            hovered = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
            pressed = StyleDictionaryColor.colorAliasInteractivePrimaryPressed,
        ),
        number = SirioColorState(
            default = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
            disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
            focused = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
            hovered = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
            pressed = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
        )
    ),
    tabs = SirioTabsColors(
        backgroundBottomSelection = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
        backgroundTopSelection = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight40,
        backgroundSelected = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
        backgroundBottomSelectionDisabled = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
        backgroundTopSelectionDisabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
        text = SirioColorState(
            default = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
            hovered = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
            focused = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
            pressed = StyleDictionaryColor.colorAliasInteractiveSecondaryDefault,
            disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
        ),
        icon = SirioColorState(
            default = StyleDictionaryColor.colorAliasTextColorPrimaryLight50,
            hovered = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
            focused = StyleDictionaryColor.colorAliasInteractivePrimaryFocus,
            pressed = StyleDictionaryColor.colorAliasAppInteractivePrimaryActive,
            disabled = StyleDictionaryColor.colorAliasTextColorDisabled,
        ),
        selection = SirioColorState(
            default = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight40,
            hovered = StyleDictionaryColor.colorAliasInteractivePrimaryHover,
            focused = StyleDictionaryColor.colorAliasInteractivePrimaryFocus,
            pressed = StyleDictionaryColor.colorAliasAppInteractivePrimary000Default,
            disabled = StyleDictionaryColor.colorAliasBackgroundColorDisabled,
        )
    ),
    searchBar = SirioSearchBarColors(
        background = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
    ),
    dialog = SirioDialogColors(
        background = StyleDictionaryColor.colorAliasBackgroundColorPrimaryLight0,
        semanticDefault = StyleDictionaryColor.colorGlobalSemanticInfo100,
        semanticAlert = StyleDictionaryColor.colorGlobalSemanticAlert100,
        semanticWarning = StyleDictionaryColor.colorGlobalSemanticWarning100,
        title = StyleDictionaryColor.colorAliasTextColorSecondaryDark100,
        text = StyleDictionaryColor.colorAliasTextColorSecondaryDark100,
    ),
    isDark = true,
)

@Keep
@Immutable
data class ButtonColors(
    val buttonFocusExtraBorder: Color,
    val buttonPrimary: SirioButtonColors,
    val buttonDanger: SirioButtonColors,
    val buttonSecondary: SirioButtonColors,
    val buttonTertiary: SirioButtonColors,
    val buttonGhost: SirioButtonColors,
) {
    companion object {
        @Stable
        val Unspecified = ButtonColors(
            buttonFocusExtraBorder = Color.Unspecified,
            buttonPrimary = SirioButtonColors.Unspecified,
            buttonDanger = SirioButtonColors.Unspecified,
            buttonSecondary = SirioButtonColors.Unspecified,
            buttonTertiary = SirioButtonColors.Unspecified,
            buttonGhost = SirioButtonColors.Unspecified,
        )
    }
}

@Keep
@Immutable
data class NotificationColors(
    val background: Color,
    val title: Color,
    val text: Color,
    val icon: Color,
    val close: Color,
    val alert: Color,
    val info: Color,
    val warning: Color,
    val success: Color,
) {
    companion object {
        @Stable
        val Unspecified = NotificationColors(
            background = Color.Unspecified,
            title = Color.Unspecified,
            text = Color.Unspecified,
            icon = Color.Unspecified,
            close = Color.Unspecified,
            alert = Color.Unspecified,
            info = Color.Unspecified,
            warning = Color.Unspecified,
            success = Color.Unspecified,
        )
    }
}
