package it.inps.sirio.foundation

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.unit.sp

val foundationTypography = SirioFoundationTypography(
    displayLgRegular = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeDisplayLg.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightDisplayLg.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontStyle(),
    ),
    displayLgMiddle = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeDisplayLg.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightDisplayLg.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightMiddle.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightMiddle.getFontStyle(),
    ),
    displayLgHeavy = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeDisplayLg.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightDisplayLg.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontStyle(),
    ),
    displayMdRegular = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeDisplayMd.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightDisplayMd.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontStyle(),
    ),
    displayMdMiddle = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeDisplayMd.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightDisplayMd.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightMiddle.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightMiddle.getFontStyle(),
    ),
    displayMdHeavy = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeDisplayMd.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightDisplayMd.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontStyle(),
    ),
    displaySmRegular = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeDisplaySm.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightDisplaySm.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontStyle(),
    ),
    displaySmMiddle = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeDisplaySm.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightDisplaySm.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightMiddle.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightMiddle.getFontStyle(),
    ),
    displaySmHeavy = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeDisplaySm.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightDisplaySm.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontStyle(),
    ),
    headlineLgRegular = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeHeadlineLg.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightHeadilineLg.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontStyle(),
    ),
    headlineLgMiddle = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeHeadlineLg.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightHeadilineLg.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightMiddle.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightMiddle.getFontStyle(),
    ),
    headlineLgHeavy = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeHeadlineLg.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightHeadilineLg.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontStyle(),
    ),
    headlineMdRegular = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = 20.sp,
        lineHeight = 28.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontStyle(),
    ),
    headlineMdMiddle = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeHeadlineMd.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightHeadilineMd.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightMiddle.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightMiddle.getFontStyle(),
    ),
    headlineMdHeavy = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeHeadlineMd.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightHeadilineMd.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontStyle(),
    ),
    headlineSmRegular = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeHeadlineSm.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightHeadilineSm.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontStyle(),
    ),
    headlineSmMiddle = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeHeadlineSm.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightHeadilineSm.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightMiddle.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightMiddle.getFontStyle(),
    ),
    headlineSmHeavy = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeHeadlineSm.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightHeadilineSm.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontStyle(),
    ),
    bodyMdRegular = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeBodyMd.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightBodyMd.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontStyle(),
    ),
    bodyMdHeavy = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeBodyMd.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightBodyMd.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontStyle(),
    ),
    bodySmRegular = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeBodySm.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightBodySm.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontStyle(),
    ),
    bodySmHeavy = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeBodySm.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightBodySm.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontStyle(),
    ),
    linkLgRegular = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = 18.sp,
        lineHeight = 25.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontStyle(),
    ),
    linkLgHeavy = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = 18.sp,
        lineHeight = 25.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontStyle(),
    ),
    linkMdRegular = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeLinkMd.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightLinkMd.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontStyle(),
    ),
    linkMdHeavy = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeLinkMd.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightLinkMd.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontStyle(),
    ),
    linkSmRegular = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeLinkSm.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightLinkSm.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontStyle(),
    ),
    linkSmHeavy = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeLinkSm.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightLinkSm.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontStyle(),
    ),
    labelMdRegular = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeLabelMd.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightLabelMd.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontStyle(),
    ),
    labelMdMiddle = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeLabelMd.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightLabelMd.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightMiddle.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightMiddle.getFontStyle(),
    ),
    labelMdHeavy = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeLabelMd.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightLabelMd.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontStyle(),
    ),
    labelSmRegular = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeLabelSm.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightLabelSm.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontStyle(),
    ),
    labelSmMiddle = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeLabelSm.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightLabelSm.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightMiddle.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightMiddle.getFontStyle(),
    ),
    labelSmHeavy = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeLabelSm.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightLabelSm.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontStyle(),
    ),
    labelNumberMdRegular = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyNumber,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeLabelNumberMd.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightLabelNumberMd.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontStyle(),
    ),
    labelNumberMdHeavy = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyNumber,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeLabelNumberMd.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightLabelNumberMd.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontStyle(),
    ),
    labelNumberSmRegular = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyNumber,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeLabelNumberSm.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightLabelNumberSm.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontStyle(),
    ),
    labelNumberSmHeavy = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyNumber,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeLabelNumberSm.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightLabelNumberSm.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontStyle(),
    ),
    signatureSerifMdRegular = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilySerif,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeSignatureMd.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightSignatureMd.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontStyle(),
    ),
    signatureSerifMdHeavy = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilySerif,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeSignatureMd.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightSignatureMd.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontStyle(),
    ),
    signatureSerifSmRegular = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilySerif,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeSignatureSm.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightSignatureSm.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontStyle(),
    ),
    signatureSerifSmHeavy = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilySerif,
        fontSize = FoundationTypography.typographyAliasFontSizeFontSizeSignatureSm.sp,
        lineHeight = FoundationTypography.typographyAliasLineHeightsLineHeightSignatureSm.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightHeavy.getFontStyle(),
    ),
    tabbarLabelXsRegular = TextStyle(
        fontFamily = FoundationTypography.typographyAliasFontFamiliesFontFamilyBase,
        fontSize = FoundationTypography.typographyGlobalFontSize1.sp,
        lineHeight = FoundationTypography.typographyGlobalLineHeights3.sp,
        fontWeight = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontWeight(),
        fontStyle = FoundationTypography.typographyAliasFontWeightsFontWeightRegular.getFontStyle(),
    ),
)

@Immutable
data class SirioFoundationTypography(
    val displayLgRegular: TextStyle,
    val displayLgMiddle: TextStyle,
    val displayLgHeavy: TextStyle,
    val displayMdRegular: TextStyle,
    val displayMdMiddle: TextStyle,
    val displayMdHeavy: TextStyle,
    val displaySmRegular: TextStyle,
    val displaySmMiddle: TextStyle,
    val displaySmHeavy: TextStyle,
    val headlineLgRegular: TextStyle,
    val headlineLgMiddle: TextStyle,
    val headlineLgHeavy: TextStyle,
    val headlineMdRegular: TextStyle,
    val headlineMdMiddle: TextStyle,
    val headlineMdHeavy: TextStyle,
    val headlineSmRegular: TextStyle,
    val headlineSmMiddle: TextStyle,
    val headlineSmHeavy: TextStyle,
    val bodyMdRegular: TextStyle,
    val bodyMdHeavy: TextStyle,
    val bodySmRegular: TextStyle,
    val bodySmHeavy: TextStyle,
    val linkLgRegular: TextStyle,
    val linkLgHeavy: TextStyle,
    val linkMdRegular: TextStyle,
    val linkMdHeavy: TextStyle,
    val linkSmRegular: TextStyle,
    val linkSmHeavy: TextStyle,
    val labelMdRegular: TextStyle,
    val labelMdMiddle: TextStyle,
    val labelMdHeavy: TextStyle,
    val labelSmRegular: TextStyle,
    val labelSmMiddle: TextStyle,
    val labelSmHeavy: TextStyle,
    val labelNumberMdRegular: TextStyle,
    val labelNumberMdHeavy: TextStyle,
    val labelNumberSmRegular: TextStyle,
    val labelNumberSmHeavy: TextStyle,
    val signatureSerifMdRegular: TextStyle,
    val signatureSerifMdHeavy: TextStyle,
    val signatureSerifSmRegular: TextStyle,
    val signatureSerifSmHeavy: TextStyle,
    val tabbarLabelXsRegular: TextStyle,
)

internal val LocalSirioFoundationTypography = staticCompositionLocalOf {
    SirioFoundationTypography(
        displayLgRegular = TextStyle.Default,
        displayLgMiddle = TextStyle.Default,
        displayLgHeavy = TextStyle.Default,
        displayMdRegular = TextStyle.Default,
        displayMdMiddle = TextStyle.Default,
        displayMdHeavy = TextStyle.Default,
        displaySmRegular = TextStyle.Default,
        displaySmMiddle = TextStyle.Default,
        displaySmHeavy = TextStyle.Default,
        headlineLgRegular = TextStyle.Default,
        headlineLgMiddle = TextStyle.Default,
        headlineLgHeavy = TextStyle.Default,
        headlineMdRegular = TextStyle.Default,
        headlineMdMiddle = TextStyle.Default,
        headlineMdHeavy = TextStyle.Default,
        headlineSmRegular = TextStyle.Default,
        headlineSmMiddle = TextStyle.Default,
        headlineSmHeavy = TextStyle.Default,
        bodyMdRegular = TextStyle.Default,
        bodyMdHeavy = TextStyle.Default,
        bodySmRegular = TextStyle.Default,
        bodySmHeavy = TextStyle.Default,
        linkLgRegular = TextStyle.Default,
        linkLgHeavy = TextStyle.Default,
        linkMdRegular = TextStyle.Default,
        linkMdHeavy = TextStyle.Default,
        linkSmRegular = TextStyle.Default,
        linkSmHeavy = TextStyle.Default,
        labelMdRegular = TextStyle.Default,
        labelMdMiddle = TextStyle.Default,
        labelMdHeavy = TextStyle.Default,
        labelSmRegular = TextStyle.Default,
        labelSmMiddle = TextStyle.Default,
        labelSmHeavy = TextStyle.Default,
        labelNumberMdRegular = TextStyle.Default,
        labelNumberMdHeavy = TextStyle.Default,
        labelNumberSmRegular = TextStyle.Default,
        labelNumberSmHeavy = TextStyle.Default,
        signatureSerifMdRegular = TextStyle.Default,
        signatureSerifMdHeavy = TextStyle.Default,
        signatureSerifSmRegular = TextStyle.Default,
        signatureSerifSmHeavy = TextStyle.Default,
        tabbarLabelXsRegular = TextStyle.Default,
    )
}